### ISSUE TITLE
Github Action: Publish to Test PyPI step

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#146]
## Description

We are already have a [github action](https://github.com/scanapi/scanapi/blob/master/.github/workflows/publish-to-pypi.yml) to publish the released version to PyPI automatically. 

But It would be nice to also have a step before it, publishing it to the Test PyPI (see discussion: https://github.com/scanapi/scanapi/pull/144#discussion_r425173742)

**Comment by vinigfer** [comment]
Is it possible to use username+password instead of token on the secrets?
Why? Github actions have it's own started action for uploading to pypi: https://github.com/actions/starter-workflows/blob/e11672e5a9026a98ce6235af089d3112ec93dbd5/ci/python-publish.yml

If we use the action from the link above, then this sounds like a simple implementation.
Just replace `twine upload dist/*` with `twine upload --repository-url https://test.pypi.org/legacy/ dist/*`

**Comment by camilamaia** [comment]
> Is it possible to use username+password instead of token on the secrets?
> Why? Github actions have it's own starter action for uploading to pypi: https://github.com/actions/starter-workflows/blob/e11672e5a9026a98ce6235af089d3112ec93dbd5/ci/python-publish.yml
> 
> If we use the action from the link above, then this sounds like a simple implementation.
> Just replace `twine upload dist/*` with `twine upload --repository-url https://test.pypi.org/legacy/ dist/*`

@vinigfer I believe this implementation is for projects that use `setup.py`. Since we migrated to poetry, we used a specific github action for that - which uses pypi token.

Just to give you a context, our solution with `setup.py` was not working that good. We were having problems to set dev envs, virtualenvs and so on. Poetry helped us with that.

**Comment by vinigfer** [comment]
OK, so I dig around a bit, and it seems we can set a Test PyPI with poetry. All we need to do is run:
```
poetry config repositories.foo https://bar.com/simple/
poetry publish --repository foo
```
Found those using `poetry config --help` and `poetry publish --help` commands.

Could you test locally if that works since I don't the token access for Test PyPI?

After we confirm that works, we can open a PR on the github action we are using. Right here: https://github.com/JRubics/poetry-publish/blob/master/entrypoint.sh#L19

**Comment by camilamaia** [comment]
@vinigfer I tested it here and it works beautiful ⭐ 

What I did:

```shell
$ poetry build
$ poetry config repositories.testpypi https://test.pypi.org/legacy/
$ poetry publish -r testpypi
```

https://test.pypi.org/project/scanapi/#description

**Comment by vinigfer** [comment]
Great!! I just opened a PR on the original action. Let's see if we get any response back.
Could you help to review it please? See if I didn't forget anything
https://github.com/JRubics/poetry-publish/pull/2/files
