### ISSUE TITLE
Github Action to tweet alerting a new release

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#148]
## Description
Github Action to tweet alerting new release

Twitter account: [@ScanAPI_](https://twitter.com/scanapi_)
We already have the dev account set up. Just need to bring the configuration to the github environment.

Similar to this: 

![image](https://user-images.githubusercontent.com/2728804/88456049-fe74e280-ce50-11ea-842d-fdf079ca17f6.png)
https://twitter.com/dangersystems/status/1258047800354504710

**Comment by barbosa** [comment]
@camilamaia https://developer.twitter.com/en

**Comment by Pradhvan** [comment]
Hi ! Just a thought we should only do this for major releases otherwise people might find it spamming from the account, if we start doing a tweet for even a minor release.

**Comment by barbosa** [comment]
@Pradhvan I don't think this will be spamming. Even minor releases won't happen that often. In fact, the latest version was published more than 16 days ago. We might be pushing things to `master` every day, but since releases are made manually after a set of features is implemented, I don't think this will be a big deal.

Major releases will rarely happen, so if we tweet only for those cases, automate the process wouldn't be worthwhile, I think.

If one day we have a real Continuous Delivery process, publishing a new version every time a PR is merged, depending on the volume of PRs, I agree we might want to reconsider this.

**Comment by camilamaia** [comment]
Hey @barbosa are you still working on this? Or should I clean the assignees up?
