### ISSUE TITLE
New feature: import a Postman collection to scanapi format

### ISSUE THREAD

**Issue by flap** [scanapi/scanapi#267]
A good improvment to this project is the feature to import a Postman collection format to scanapi format!

**Comment by camilamaia** [comment]
Wow, this one would be awesome 😻

**Comment by leogregianin** [comment]
Sorry for closing the issue, I typed wrong.

It would be interesting for Insomnia collection too.

**Comment by BrunoPontesLira** [comment]
Esta rolando a integração com arquivos Postman?

**Comment by camilamaia** [comment]
@BrunoPontesLira no, not yet, unfortunately. It is still an open issue.

**Comment by hebertjulio** [comment]
Hey @scanapi/core-team ,

Just for the sake of knowledge, which postman file should be read to generate the ScanAPI spec.

Thanks.

**Comment by BrunoPontesLira** [comment]
I think it's the Collections and Environments files.

**Comment by camilamaia** [comment]
We decided that we will implement only one official converter: ScanAPI <=> OpenAPI. But, we will create a plugin architecture, so the community will be able to create other converters and use it. Otherwise, it would be too much to maintain many different official converters.

For this reason, I will close this issue, ok?

https://github.com/scanapi/scanapi/issues/12#issuecomment-889932655

**Comment by sr2ds** [comment]
Hello guys, 
Some change about official converter?
Thanks
