### ISSUE TITLE
Add request name to results variable passed to report

### ISSUE THREAD

**Issue by leandro-hermes** [scanapi/scanapi#354]
I would like to show the name I have defined for each request in the report, but it is not currently being passed. I need this because I have many similar endpoints and I need to open them one by one to find the details of the request I want to see. I would like also visually group some requests by their name using Javascript.

**Comment by hebertjulio** [comment]
@camilamaia I can try working on this issue. :)

**Comment by hebertjulio** [comment]
Hey @camilamaia, I need someone confirm if request name that should can show is name field in RequestNode class, and also a suggestion how and where request name should be shown on report template.

**Comment by hebertjulio** [comment]
Maybe, as a suggestion, we could show the name of the request in front of the path as openapi.

![empire_nolinks(1)](https://user-images.githubusercontent.com/4763091/120028109-a6f05780-bfca-11eb-9e91-024c48f71160.jpg)

**Comment by camilamaia** [comment]
@hebertjulio 

About which name to show, I can see two possibilities here:
1. [RequestNode name property](https://github.com/scanapi/scanapi/blob/master/scanapi/tree/request_node.py#L70-L72) as you said. 
Ex: `my_request_name`
2. We could create a full_name property for `RequestNode`, the same way we have the [TestingNode full_name property](https://github.com/scanapi/scanapi/blob/master/scanapi/tree/testing_node.py#L33-L35). 
Ex: `my_endppint_name::my_request_name`

About where to place the name, I can see two possible places:
1. Right after the url path, as you suggested
2. Right below the url path

Putting all together, we have:

Option 1:

![image](https://user-images.githubusercontent.com/2728804/120032734-fe91c180-bfd0-11eb-8ba6-81f203efc06f.png)

Option 2

![image](https://user-images.githubusercontent.com/2728804/120032902-431d5d00-bfd1-11eb-80d2-beee1145c3d0.png)

Option 3

![image](https://user-images.githubusercontent.com/2728804/120032076-0dc43f80-bfd0-11eb-8f82-a8d5c3c8e35c.png)

Option 4

![image](https://user-images.githubusercontent.com/2728804/120032995-621bef00-bfd1-11eb-9ea8-65706d9af404.png)

My vote is for option 1. Showing the names of the endpoints might get too long if there are multiple nested endpoints. And the URL path already gives us a sort of context.

But if we decide to go with the full_name, then I prefer option 3, because we have more space to show big names.

What do you think? @scanapi/core-team any thoughts here? @djalmaaraujo ?

**Comment by hebertjulio** [comment]
Hey @camilamaia ,

I think if request name is sufficient to identify it, first option is great, but if isn't, option third option is my choice.

**Comment by camilamaia** [comment]
@hebertjulio perfect, let's go with option 1 then.

**Comment by hebertjulio** [comment]
Hey, 

I'm having trouble defining a description of the run() method, the only description that comes to mind is "Run requests" :smile: 

https://github.com/scanapi/scanapi/blob/67ac683de32d44355ebc3cdc97f1361c8f2b781b/scanapi/tree/request_node.py#L117

**Comment by camilamaia** [comment]
@hebertjulio this description is fine for me haha 👍
