### ISSUE TITLE
Add unit tests for `test_get_specs.py` and `test_run.py` 

### ISSUE THREAD

**Issue by Pradhvan** [scanapi/scanapi#433]
[test_get_specs.py](https://github.com/scanapi/scanapi/blob/main/tests/unit/tree/endpoint_node/test_get_specs.py) and [test_run.py](https://github.com/scanapi/scanapi/blob/main/tests/unit/tree/endpoint_node/test_run.py) both require unit tests which is also being flagged in our [static analysis](https://deepsource.io/gh/scanapi/scanapi/issue/PYL-W0511/occurrences?page=1). 

[ScanAPI Writing Tests Documentation](https://github.com/scanapi/scanapi/wiki/Writing-Tests)

**Comment by LoremIpsum42** [comment]
I have a question regarding the function _get_specs. Inside this function you are merging two dictionaries. This merging does work for "parameter" and "headers" since in this scenario the keys are different most of the time between parent and node. However, for all the other attributes this function doesn't merge the two dictionaries into one, because the key is always the same. Is this intended? Also, the merging process is not working for the path element at all. If this behavior is not intended we should maybe first fix the function before writing tests.
Example:
`
parent = EndpointNode({"name": "root"})
node = EndpointNode({"name": "child-node"}, parent=parent)
values = node.spec.get("name", {})
parent_values = getattr(node.parent, "name", None)
print({**parent_values, **values})
`
Output: {'name': 'child-node'}

I recognize,that this function only seems to be used for the keys "params" and "headers". So maybe this function doesn't need to work for other attributes?

**Comment by rafaquelhodev** [comment]
Hi guys, I've just raised a PR for this issue! Cheers =)
